# Generated by Django 3.0.4 on 2020-03-26 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='courses',
        ),
        migrations.DeleteModel(
            name='MemberShip',
        ),
    ]
