# Generated by Django 3.0.2 on 2020-03-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0003_auto_20200326_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ManyToManyField(to='ed.Profile'),
        ),
    ]
