# Generated by Django 3.0.2 on 2020-03-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0006_chats_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='users',
        ),
        migrations.AddField(
            model_name='chats',
            name='users',
            field=models.ManyToManyField(to='ed.Profile'),
        ),
    ]
