# Generated by Django 3.0.2 on 2020-03-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0007_auto_20200327_0520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='chats',
            new_name='messages',
        ),
    ]
