# Generated by Django 3.0.2 on 2020-03-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0008_auto_20200327_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='messages',
        ),
        migrations.AddField(
            model_name='chats',
            name='messages',
            field=models.ManyToManyField(to='ed.Message'),
        ),
    ]
