# Generated by Django 3.0.2 on 2020-03-27 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0009_auto_20200327_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(through='ed.ChatMembership', to='ed.Profile')),
                ('messages', models.ManyToManyField(to='ed.Message')),
            ],
        ),
        migrations.DeleteModel(
            name='Chats',
        ),
        migrations.AddField(
            model_name='chatmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed.Group'),
        ),
        migrations.AddField(
            model_name='chatmembership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed.Profile'),
        ),
    ]
