# Generated by Django 3.0.2 on 2020-03-27 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0012_auto_20200327_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmembership',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ed.Group'),
        ),
        migrations.AlterField(
            model_name='chatmembership',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ed.Profile'),
        ),
    ]
