# Generated by Django 3.0.2 on 2020-03-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0013_auto_20200327_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
