# Generated by Django 3.0.2 on 2020-03-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0014_remove_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='ed.ChatMembership', to='ed.Profile'),
        ),
    ]
