# Generated by Django 3.0.2 on 2020-03-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0017_profile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
